import React from 'react';

const About: React.FC = () => {
  return (
    <section className="py-24 px-6 md:px-12 max-w-4xl mx-auto min-h-[60vh] flex flex-col justify-center relative z-10">
      <div className="space-y-12">
        <h2 className="text-xs text-zinc-500 tracking-[0.3em] uppercase border-b border-zinc-900 pb-4 inline-block">
          About The Frequency
        </h2>
        
        <div className="space-y-8 text-xl md:text-3xl font-light leading-relaxed text-zinc-200">
          <p>
            We are drifting through a new era of creation. 
            <span className="text-zinc-500 mx-2">///</span>
            Where human intuition guides machine precision.
          </p>
          <p>
            <span className="text-white">Uncle B Laced It</span> is not just beats. It is a dialogue between flesh and silicon. 
            We curate moments of spiritual grounding and late-night introspection, using AI as an instrument—not a replacement.
          </p>
          <p className="text-base md:text-lg text-zinc-500 pt-8 max-w-2xl">
            Resonance is the only metric that matters. Whether generated by neural networks or played by human hands, if the feeling is real, the sound is true.
          </p>
        </div>
      </div>
    </section>
  );
};

export default About;